import { includeHTML } from './include.js';

includeHTML('/html/guide/heading.html', '#heading');
includeHTML('/html/guide/link.html', '#link');
includeHTML('/html/guide/text.html', '#text');
includeHTML('/html/guide/checkbox.html', '#checkbox');
includeHTML('/html/guide/radio.html', '#radio');
includeHTML('/html/guide/select.html', '#select');
includeHTML('/html/guide/button.html', '#button');
includeHTML('/html/guide/input.html', '#input');
includeHTML('/html/guide/chip.html', '#chip');
includeHTML('/html/guide/dialog.html', '#dialog');
includeHTML('/html/guide/badge.html', '#badge');
includeHTML('/html/guide/popup.html', '#popup');
includeHTML('/html/guide/list.html', '#list');
includeHTML('/html/guide/header.html', '#header');
includeHTML('/html/guide/card.html', '#card');
includeHTML('/html/guide/footer.html', '#footer');
includeHTML('/html/guide/checklabel.html', '#checklabel');
includeHTML('/html/guide/details.html', '#details');
includeHTML('/html/guide/tab.html', '#tab');
includeHTML('/html/guide/listTitle.html', '#listTitle');
includeHTML('/html/guide/cta.html', '#cta');
includeHTML('/html/guide/calendar.html', '#calendar');
